version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2 
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g  # Adjust the memory limit as needed
    networks:
      - default


  # Test Postgres Setup for Connector
  postgres:
    image: postgres:16
    container_name: postgres
    command: ["docker-entrypoint.sh", "postgres"]
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tests/connector/postgresql.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default


networks:
  default:
    name: data_catalog